$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$wrapper = Join-Path $root "invoke_governed_migration.ps1"

function Invoke-Wrapper([string]$InputJsonPath, [string]$OutputDir) {
    $cmd = "& '$wrapper' -InputJsonPath '$InputJsonPath' -OutputDir '$OutputDir'"
    $raw = & powershell.exe -NoProfile -ExecutionPolicy Bypass -Command $cmd 2>&1 | Out-String
    $code = $LASTEXITCODE

    $txt = $raw.Trim()
    $s = $txt.IndexOf('{')
    $e = $txt.LastIndexOf('}')
    if ($s -lt 0 -or $e -lt 0 -or $e -le $s) {
        throw "Cannot parse JSON from wrapper output. Raw: $raw"
    }
    $jsonText = $txt.Substring($s, $e - $s + 1)
    try { $obj = $jsonText | ConvertFrom-Json } catch { throw "Invalid JSON wrapper output. Raw: $raw" }

    return [PSCustomObject]@{
        ExitCode = $code
        Object   = $obj
        Raw      = $raw
    }
}

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
}

function New-BaseInput([string]$mode) {
    return [ordered]@{
        migrationId       = "MIG-WRAPPER-001"
        proposalId        = "DBCR-WRAPPER-001"
        environment       = "TEST"
        mode              = $mode
        operator          = "test-runner"
        approval          = @{ approved = $true; by = "human" }
        riskSummary       = @{ allowed = $true; level = "Low" }
        recoveryReadiness = @{ ready = $true; recoveryMode = "A" }
        schemaDiffSummary = @{ safe = $true; finalStatus = "PASS" }
        executionPlan     = @{ steps = @("validate", "report") }
    }
}

$tmpRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("governed-wrapper-" + [Guid]::NewGuid().ToString("n"))
New-Item -ItemType Directory -Path $tmpRoot -Force | Out-Null

try {
    # Case 1: MOCK success
    $mockInputPath = Join-Path $tmpRoot "mock_input.json"
    (New-BaseInput "MOCK" | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $mockInputPath -Encoding UTF8
    $mockOut = Join-Path $tmpRoot "out_mock"
    $r = Invoke-Wrapper -InputJsonPath $mockInputPath -OutputDir $mockOut
    Assert-True ($r.ExitCode -eq 0) "[MOCK] expected exit 0"
    Assert-True ($r.Object.success -eq $true) "[MOCK] expected success=true"
    Assert-True ($r.Object.executed -eq $false) "[MOCK] expected executed=false"
    Assert-True ($r.Object.mode -eq "MOCK") "[MOCK] expected mode=MOCK"
    Assert-True ($r.Object.reportGenerated -eq $true) "[MOCK] expected reportGenerated=true"

    # Ensure report files generated by report_generator
    Assert-True (Test-Path -LiteralPath (Join-Path $mockOut "execution_report.json")) "[MOCK] missing execution_report.json"
    Assert-True (Test-Path -LiteralPath (Join-Path $mockOut "execution_report.md")) "[MOCK] missing execution_report.md"
    Assert-True (Test-Path -LiteralPath (Join-Path $mockOut "risk_summary.md")) "[MOCK] missing risk_summary.md"
    Assert-True (Test-Path -LiteralPath (Join-Path $mockOut "schema_diff_summary.md")) "[MOCK] missing schema_diff_summary.md"
    Assert-True (Test-Path -LiteralPath (Join-Path $mockOut "recovery_readiness_summary.md")) "[MOCK] missing recovery_readiness_summary.md"

    # Case 2: DRY_RUN success
    $dryInputPath = Join-Path $tmpRoot "dry_input.json"
    (New-BaseInput "DRY_RUN" | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $dryInputPath -Encoding UTF8
    $dryOut = Join-Path $tmpRoot "out_dry"
    $r = Invoke-Wrapper -InputJsonPath $dryInputPath -OutputDir $dryOut
    Assert-True ($r.ExitCode -eq 0) "[DRY_RUN] expected exit 0"
    Assert-True ($r.Object.success -eq $true) "[DRY_RUN] expected success=true"
    Assert-True ($r.Object.mode -eq "DRY_RUN") "[DRY_RUN] expected mode=DRY_RUN"

    # Case 3: LIVE_EXECUTE must fail
    $liveInputPath = Join-Path $tmpRoot "live_input.json"
    (New-BaseInput "LIVE_EXECUTE" | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $liveInputPath -Encoding UTF8
    $r = Invoke-Wrapper -InputJsonPath $liveInputPath -OutputDir (Join-Path $tmpRoot "out_live")
    Assert-True ($r.ExitCode -eq 1) "[LIVE] expected exit 1"
    Assert-True ($r.Object.success -eq $false) "[LIVE] expected success=false"
    Assert-True ($r.Object.reason -eq "LIVE_EXECUTE is not supported in this phase") "[LIVE] expected reason"

    # Case 4: approval not approved -> fail
    $bad = New-BaseInput "MOCK"
    $bad.approval = @{ approved = $false }
    $badPath = Join-Path $tmpRoot "bad_approval.json"
    ($bad | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $badPath -Encoding UTF8
    $r = Invoke-Wrapper -InputJsonPath $badPath -OutputDir (Join-Path $tmpRoot "out_bad_approval")
    Assert-True ($r.ExitCode -eq 1) "[APPROVAL] expected exit 1"
    Assert-True ($r.Object.success -eq $false) "[APPROVAL] expected success=false"

    # Case 5: recoveryReadiness not ready -> fail
    $bad = New-BaseInput "MOCK"
    $bad.recoveryReadiness = @{ ready = $false }
    $badPath = Join-Path $tmpRoot "bad_recovery.json"
    ($bad | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $badPath -Encoding UTF8
    $r = Invoke-Wrapper -InputJsonPath $badPath -OutputDir (Join-Path $tmpRoot "out_bad_recovery")
    Assert-True ($r.ExitCode -eq 1) "[RECOVERY] expected exit 1"
    Assert-True ($r.Object.success -eq $false) "[RECOVERY] expected success=false"

    # Case 6: riskSummary not allowed -> fail
    $bad = New-BaseInput "MOCK"
    $bad.riskSummary = @{ allowed = $false }
    $badPath = Join-Path $tmpRoot "bad_risk.json"
    ($bad | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $badPath -Encoding UTF8
    $r = Invoke-Wrapper -InputJsonPath $badPath -OutputDir (Join-Path $tmpRoot "out_bad_risk")
    Assert-True ($r.ExitCode -eq 1) "[RISK] expected exit 1"
    Assert-True ($r.Object.success -eq $false) "[RISK] expected success=false"

    # Case 7: schemaDiffSummary not safe -> fail
    $bad = New-BaseInput "MOCK"
    $bad.schemaDiffSummary = @{ safe = $false }
    $badPath = Join-Path $tmpRoot "bad_schema.json"
    ($bad | ConvertTo-Json -Depth 20) | Set-Content -LiteralPath $badPath -Encoding UTF8
    $r = Invoke-Wrapper -InputJsonPath $badPath -OutputDir (Join-Path $tmpRoot "out_bad_schema")
    Assert-True ($r.ExitCode -eq 1) "[SCHEMA] expected exit 1"
    Assert-True ($r.Object.success -eq $false) "[SCHEMA] expected success=false"

    # Case 8: report files generated already checked in success path
    # Case 9: no dependency on tenant_service_limits.sql
    Assert-True ($r.Raw -notmatch "tenant_service_limits") "[NO_TSL_DEP] unexpected tenant_service_limits mention"

    Write-Output "PASS: test_invoke_governed_migration.ps1"
}
finally {
    # Keep temp artifacts for post-run inspection if needed.
    Write-Output "INFO: temp files kept at $tmpRoot"
}

